name: Debian 12 RDP

on:
  workflow_dispatch:

jobs:
  debian-rdp:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm-slim
      options: --privileged --security-opt seccomp=unconfined

    steps:
      - name: Update System and Install Dependencies
        run: |
          apt-get update
          apt-get install -y sudo curl wget gnupg2 systemd

      - name: Install XFCE Desktop
        run: |
          DEBIAN_FRONTEND=noninteractive apt-get install -y \
            xfce4 \
            xfce4-goodies \
            xorg \
            dbus-x11 \
            x11-utils

      - name: Install RDP and Browser
        run: |
          DEBIAN_FRONTEND=noninteractive apt-get install -y \
            xrdp \
            firefox-esr \
            thunar \
            xfce4-terminal \
            netcat

      - name: Configure XRDP
        run: |
          echo 'xfce4-session' > /root/.xsession
          cat > /etc/xrdp/startwm.sh << 'EOF'
#!/bin/sh
if [ -r /etc/default/locale ]; then
  . /etc/default/locale
  export LANG LANGUAGE
fi
startxfce4
EOF
          chmod +x /etc/xrdp/startwm.sh

      - name: Create RDP User
        run: |
          # Generate secure password
          PASSWORD=$(openssl rand -base64 12 | tr -d '/+=' | cut -c1-12)
          echo "RDP_PASSWORD=$PASSWORD" >> $GITHUB_ENV
          
          # Create user
          useradd -m -s /bin/bash -G sudo rdplinux
          echo "rdplinux:$PASSWORD" | chpasswd
          
          # Setup user session
          mkdir -p /home/rdplinux/.config
          echo 'xfce4-session' > /home/rdplinux/.xsession
          chown -R rdplinux:rdplinux /home/rdplinux

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          # Start tailscaled in background
          tailscaled --state=mem: &

      - name: Connect Tailscale
        run: |
          sleep 10
          tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=debian12-$GITHUB_RUN_ID
          TS_IP=$(tailscale ip -4)
          echo "TAILSCALE_IP=$TS_IP" >> $GITHUB_ENV
          
          if [ -z "$TS_IP" ]; then
            echo "❌ Failed to get Tailscale IP"
            # Try alternative method
            sleep 5
            TS_IP=$(tailscale ip -4 2>/dev/null || echo "")
            if [ -n "$TS_IP" ]; then
              echo "TAILSCALE_IP=$TS_IP" >> $GITHUB_ENV
            else
              exit 1
            fi
          fi

      - name: Start RDP Services
        run: |
          # Start DBUS
          dbus-daemon --system --fork
          
          # Start RDP services
          xrdp-sesman &
          xrdp &
          
          sleep 5
          
          # Check if RDP is running
          if ps aux | grep -q [x]rdp; then
            echo "✅ RDP services started successfully"
          else
            echo "❌ RDP services failed to start"
            exit 1
          fi

      - name: Show Connection Information
        run: |
          echo ""
          echo "🖥️  ===== DEBIAN 12 RDP ACCESS ====="
          echo "📍 IP Address: $TAILSCALE_IP"
          echo "👤 Username: rdplinux"
          echo "🔑 Password: $RDP_PASSWORD"
          echo "🔌 Port: 3389"
          echo "🐧 OS: Debian 12 (Bookworm)"
          echo "📁 Desktop: XFCE"
          echo "🌐 Browser: Firefox ESR"
          echo "================================"
          echo ""
          echo "💡 Connect using:"
          echo "rdesktop -u rdplinux -p $RDP_PASSWORD $TAILSCALE_IP"
          echo "or"
          echo "xfreerdp /u:rdplinux /p:$RDP_PASSWORD /v:$TAILSCALE_IP"

      - name: Keep Session Alive
        run: |
          echo "🔄 Debian 12 RDP session is now active!"
          echo "⏰ This session will run for 1 hour maximum"
          echo "⏹️  To stop: Cancel this workflow in GitHub Actions"
          echo ""
          COUNTER=0
          while [ $COUNTER -lt 72 ]; do
            MINUTES=$((COUNTER * 5))
            echo "✅ Session active - ${MINUTES} minutes elapsed"
            sleep 300
            COUNTER=$((COUNTER + 1))
          done
          echo "🕒 Maximum time reached, session ending"
