name: Debian 12 RDP Desktop

on:
  workflow_dispatch:

jobs:
  debian-rdp:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm-slim
      options: --privileged

    steps:
      - name: Update and install basic packages
        run: |
          apt-get update
          apt-get install -y sudo curl wget

      - name: Install XFCE desktop
        run: |
          DEBIAN_FRONTEND=noninteractive apt-get install -y \
            xfce4 \
            xfce4-goodies \
            xorg \
            xrdp \
            firefox-esr

      - name: Create RDP user
        run: |
          PASSWORD=$(openssl rand -base64 12 | tr -d '/+=' | cut -c1-12)
          echo "RDP_PASSWORD=$PASSWORD" >> $GITHUB_ENV
          
          useradd -m -s /bin/bash rdplinux
          echo "rdplinux:$PASSWORD" | chpasswd
          usermod -a -G sudo rdplinux
          
          echo 'xfce4-session' > /home/rdplinux/.xsession
          chown rdplinux:rdplinux /home/rdplinux/.xsession

      - name: Configure XRDP
        run: |
          echo 'xfce4-session' > ~/.xsession
          cat > /etc/xrdp/startwm.sh << 'EOF'
#!/bin/bash
if [ -r /etc/default/locale ]; then
  . /etc/default/locale
  export LANG LANGUAGE
fi
startxfce4
EOF
          chmod +x /etc/xrdp/startwm.sh

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Start Tailscale and RDP
        run: |
          # Start tailscaled
          tailscaled --state=mem: &
          sleep 10
          
          # Connect to Tailscale
          tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=debian12-$GITHUB_RUN_ID
          TS_IP=$(tailscale ip -4)
          echo "TAILSCALE_IP=$TS_IP" >> $GITHUB_ENV
          
          # Start RDP
          xrdp-sesman &
          xrdp &
          sleep 5

      - name: Display connection info
        run: |
          echo "=========================================="
          echo "🖥️  DEBIAN 12 RDP READY"
          echo "=========================================="
          echo "IP: $TAILSCALE_IP"
          echo "User: rdplinux"
          echo "Password: $RDP_PASSWORD"
          echo "Port: 3389"
          echo "=========================================="

      - name: Keep alive
        run: |
          echo "RDP session will stay active for 1 hour..."
          sleep 3600
