name: Debian 12 RDP

on:
  workflow_dispatch:

jobs:
  debian-rdp:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm-slim

    steps:
      - name: Update and Install Dependencies
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y \
            sudo \
            curl \
            wget \
            gnupg \
            systemd

      - name: Install Desktop Environment
        run: |
          DEBIAN_FRONTEND=noninteractive apt-get install -y \
            xfce4 \
            xfce4-goodies \
            xorg \
            xrdp \
            firefox-esr \
            thunar \
            xfce4-terminal \
            netcat

      - name: Configure XRDP
        run: |
          echo 'xfce4-session' > ~/.xsession
          tee /etc/xrdp/startwm.sh > /dev/null <<'EOF'
          #!/bin/sh
          if [ -r /etc/default/locale ]; then
            . /etc/default/locale
            export LANG LANGUAGE
          fi
          startxfce4
          EOF
          chmod +x /etc/xrdp/startwm.sh

      - name: Create RDP User
        run: |
          # Generate secure password
          PASSWORD=$(openssl rand -base64 12 | tr -d '/+=' | cut -c1-12)
          echo "RDP_PASSWORD=$PASSWORD" >> $GITHUB_ENV
          
          # Create user
          useradd -m -s /bin/bash rdplinux
          echo "rdplinux:$PASSWORD" | chpasswd
          usermod -a -G sudo rdplinux
          
          # Setup user session
          sudo -u rdplinux mkdir -p /home/rdplinux/.config
          sudo -u rdplinux echo 'xfce4-session' > /home/rdplinux/.xsession

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          tailscaled --state=mem: &

      - name: Connect Tailscale
        run: |
          sleep 10
          tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=debian12-$GITHUB_RUN_ID
          TS_IP=$(tailscale ip -4)
          echo "TAILSCALE_IP=$TS_IP" >> $GITHUB_ENV
          
          if [ -z "$TS_IP" ]; then
            echo "❌ Failed to get Tailscale IP"
            exit 1
          fi

      - name: Start RDP Service
        run: |
          # Start RDP services
          xrdp-sesman &
          xrdp &
          sleep 5
          
          # Test RDP service
          if nc -z localhost 3389; then
            echo "✅ RDP service started successfully"
          else
            echo "❌ RDP service failed to start"
            exit 1
          fi

      - name: Show Connection Info
        run: |
          echo ""
          echo "🖥️  ===== DEBIAN 12 RDP ACCESS ====="
          echo "📍 IP Address: $TAILSCALE_IP"
          echo "👤 Username: rdplinux"
          echo "🔑 Password: $RDP_PASSWORD"
          echo "🔌 Port: 3389"
          echo "🐧 OS: Debian 12 (Bookworm)"
          echo "================================"
          echo ""

      - name: Keep Alive
        run: |
          echo "🔄 Debian 12 RDP session is active for 1 hour"
          echo "⏹️  To stop: Cancel this workflow in GitHub Actions"
          COUNTER=0
          while [ $COUNTER -lt 72 ]; do
            echo "⏰ Running... ($((COUNTER * 5)) minutes)"
            sleep 300
            COUNTER=$((COUNTER + 1))
          done
